### PR TITLE
Make equals work with Schematics

### PR DESCRIPTION
**Pull request by toddsifleet**

### CODE REVIEW

**Comment by toddsifleet** [comment]
Schematics doesn't work with python 3.2, I will try to recreate the failure without schematics.

**Comment by UberFarmer** [comment]
Looks great -- do we want to consider supporting the case (it seems unlikely to me) when you have a real object you're making allowances about, and you have a fuzzy equals object in the code-under-test?

**Comment by toddsifleet** [comment]
@UberFarmer I'm not sure what you mean, could you give an example?

**Comment by UberFarmer** [comment]
Basically, the question is do we want to think about supporting testing on code that uses equals? My gut tells me no, but there may be some valid reasons to do the following?

```python
def foo():
    fuzzy_object = instance_of(Baz)
    bar(fuzzy_object)
```

**Comment by toddsifleet** [comment]
@UberFarmer I say we cross that bridge when we come to it, no need to add features we don't need.

**Pull request closed without merging**
